//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayNGo.FraceMarteja.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerGroup
    {
        public int Id { get; set; }
        public Nullable<int> Group_Id { get; set; }
        public Nullable<int> Player_Id { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Player Player { get; set; }
    }
}
